//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseManagementModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnrollCourse
    {
        public string EnrollID { get; set; }
        public System.DateTime DateEnrolled { get; set; }
        public string StudentID { get; set; }
        public string ClassID { get; set; }
    
        public virtual ClassRoom ClassRoom { get; set; }
        public virtual Person Person { get; set; }
    }
}
