//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseManagementModels
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;

    public partial class TeacherInfo : DbContext
    {
        public string TeacherID { get; set; }
        public string TeacherLevel { get; set; }
        public string CurrentJobName { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
